### ISSUE TITLE
USER STORY: title

### ISSUE THREAD

**Issue by mjjstockman** [mjjstockman/ecomm#15]
As a **Site User** I can **create a username and password** so that **I can sign up to the site**

# Acceptance Criteria

 - Registration is only available to anonymous users
 - I can enter my information needed to sign up to the site
 - The page contains a form with Email, Email Confirmation, Username, Password, Password Confirmation fields and a submit button
 - My entered information is validated
 - My entered information is saved
 - A clear reason for signing up to the site is given

# Tasks

- [x] Install and set up Allauth
- [x] Create base template
- [x] Add base template to Allauth templates
- [x] Add crispy forms
- [x] Manually test sign up process
