### ISSUE TITLE
USER STORY: Log in using username and password

### ISSUE THREAD

**Issue by mjjstockman** [mjjstockman/ecomm#18]
As a **Site User** I can **log in to the site with my username and password** so that **I can use all site features**

# Acceptance Criteria

 - Log in is only available to anonymous users
 - Clicking on the login link takes me to the log in page
 - The page contains a form with Username, Password and a submit button
 - Filling in the form with correct data logs me in
 - Once logged in I am taken to the home page
 - Log in is role-based

# Tasks

- [x] Make log in only available to anonymous users
- [x] Redirect to the home page
- [x] Manually test login process
