### ISSUE TITLE
USER STORY: Login state

### ISSUE THREAD

**Issue by mjjstockman** [mjjstockman/ecomm#21]
As a **Site User** I can **be shown if I am logged in** so that **I know if I am am logged in or not**

# Acceptance Criteria

 - I am shown if I am logged in
 - I am shown if I am not logged in

# Tasks

- [x] Add message making it clear a user is logged in
- [x] Change nav to logout if user is logged in
- [x] Show login link if user not logged in
