### ISSUE TITLE
USER STORY: Add product to site

### ISSUE THREAD

**Issue by mjjstockman** [mjjstockman/ecomm#24]
As a **Site Owner** I can **add products to the site through the User Interface** so that **new goods can be addeed without having to go through site admin**

# Acceptance Criteria

 - I can add products to the site 
 - An image can be added
 - A description can be added
 - A price can be added

# Tasks

- [x] Create products app and add to settings
- [x] Create products model, view, urls and template
- [x] Create form
- [x] Validate form
- [x] Save data
- [x] Manually test adding a product
