### ISSUE TITLE
USER STORY: View all products

### ISSUE THREAD

**Issue by mjjstockman** [mjjstockman/ecomm#25]
As a **Site User** I can **view the goods on sale** so that **I can see if there is anything I would want to purchase**

# Acceptance Criteria

 - I can see an image of all products
 - I can see a description of all products
 - I can see the price of all products
 

# Tasks

- [x] Add products app
- [x] Add products image, description and price to the database
- [x] Show all information to the user
