### ISSUE TITLE
USER STORY: Search products by category

### ISSUE THREAD

**Issue by mjjstockman** [mjjstockman/ecomm#26]
As a **Site User** I can **sort the goods on sale by relevant categories** so that **I can see easily navigate the goods**

# Acceptance Criteria

- I can choose a category of goods from the relevant page
- ADD CATEGORIES
- This displays the goods from the selected category

# Tasks

- [x] Add query to URL
- [x] Import Q and generate search query
- [x] Manually test viewing all categories
