### ISSUE TITLE
USER STORY: Edit products on site

### ISSUE THREAD

**Issue by mjjstockman** [mjjstockman/ecomm#27]
As a **Site Owner** I can **edit products on the site** so that **any mistakes can be corrected or changes made**

# Acceptance Criteria

 - I can edit products on the site 
 - I am asked to confirm if the edit is correct

# Tasks

 view, urls and template
- [x] Create products/edit/<str:pk>/ url
- [x] Create view
- [x] Use pre-populated products/add form
- [x] Save updates
- [x] Manually test updating a product
