### ISSUE TITLE
USER STORY: Delete product from site

### ISSUE THREAD

**Issue by mjjstockman** [mjjstockman/ecomm#28]
As a **Site Owner** I can **delete products from the site** so that **goods can be removed from being able to be purchased**

# Acceptance Criteria

 - I can delete products from the site 
 - I am asked to confirm if I want to delete the product

# Tasks

- [x] Create a delete button
- [x] Create confirm delete section 
- [x] Implement product deletion
