### ISSUE TITLE
USER STORY: Know if an order was successful

### ISSUE THREAD

**Issue by mjjstockman** [mjjstockman/ecomm#34]
As a **Site User** I can **be shown a message after placing an order** so that **I know if the order was successful or not**

# Acceptance Criteria

 - A successful order displays a message informing the user that everything was OK and the order was placed
 - An unsuccessful order displays a message informing the user that the order was not placed 
 - An unsuccessful order displays a helpful message informing the user why the order was not successful 

# Tasks

- [x] Add a confirmation message once an order is successfully placed
- [x] Add a notification message if an order is unsuccessful 
- [x] Explain in the unsuccessful message what was wrong
