### ISSUE TITLE
USER STORY: Edit products on site backend

### ISSUE THREAD

**Issue by mjjstockman** [mjjstockman/ecomm#37]
As a **Site Owner** I can **edit products** so that **it's I can make relevant changes**

# Acceptance Criteria

 - I can edit product info through Django admin

# Tasks

- [x] Create products app
- [x] Create products class
- [x] Add to admin
