### ISSUE TITLE
USER STORY: Delete products through admin

### ISSUE THREAD

**Issue by mjjstockman** [mjjstockman/ecomm#38]
As a **Site Owner** I can **delete products** so that **I can remove them remove them from the site**

# Acceptance Criteria

 - I can edit product info through Django admin

# Tasks

- [x] Create products app
- [x] Create products class
- [x] Add to admin
