### ISSUE TITLE
USER STORY: View past events

### ISSUE THREAD

**Issue by mjjstockman** [mjjstockman/ecomm#45]
As a **Site User** I can **see a selection of events Get Wurst have catered for** so that **I can gauge their reputation and see if they could be suitable for an event**

# Acceptance Criteria

 - I can look at events on the events page
 - Info includes an image, the event name, a link to the event and a date they worked.

# Tasks

- [x] Create events app
- [x] Create events model
- [x] Add events url
- [x] Show events info on events page
