### ISSUE TITLE
USER STORY: See previous events

### ISSUE THREAD

**Issue by mjjstockman** [mjjstockman/ecomm#8]
As a **Site User** I can **view events Get Wurst have previously worked** so that **I can gauge their professionalism and suitability**

# Acceptance Criteria

 - An area on the site shows examples of previous events.
 - There is an image, a description and date.

# Tasks

- [ ] Add failing test to create an Event object.
- [ ] Pass the test.
- [ ] Refractor
- [ ] Add Event class to admin.

- [ ] Add failing test to add a description to an Event instance.
- [ ] Pass the test.
- [ ] Refractor

- [ ] Add failing test to add a date to an Event instance.
- [ ] Pass the test.
- [ ] Refractor

- [ ] Add failing test to add an image to an Event instance.
- [ ] Pass the test.
- [ ] Refractor
